/*!
 * Brújula Electoral IA — Módulo "Análisis territorial" (Soacha)
 * Uso: <script src="js/analisis-soacha.js" defer> (cerrar la etiqueta script) antes de </body>.
 * Se integra como tercera pestaña junto a "Candidatos | Partidos y tendencias".
 * Si no encuentra esa barra, crea un botón flotante. API: window.BrujulaTerritorial.open()/close()
 */
(function () {
  'use strict';
  if (window.BrujulaTerritorial) return;

  const D = {"meta":{"municipio":"Soacha","anio":2023,"previo":2019},"resumen":{"ASAMBLEA":{"m19":{"validos":78108,"tarjetas":139149,"blanco":0.2791,"nulo":0.0687,"nomarcado":0.0909,"logo":0.2667,"nep":8.1162},"m23":{"validos":96293,"tarjetas":164614,"blanco":0.2526,"nulo":0.0639,"nomarcado":0.0986,"logo":0.4062,"nep":8.3657},"g19":"PARTIDO SOCIAL DE UNIDAD NACIONAL  PARTIDO DE LA U","g23":"PACTO HISTÓRICO"},"CONCEJO":{"m19":{"validos":105354,"tarjetas":140072,"blanco":0.1466,"nulo":0.0545,"nomarcado":0.0468,"logo":0.1376,"nep":12.062},"m23":{"validos":129079,"tarjetas":172391,"blanco":0.1482,"nulo":0.0476,"nomarcado":0.0554,"logo":0.2371,"nep":14.1351},"g19":"PARTIDO CAMBIO RADICAL","g23":"PACTO HISTORICO"},"JAL":{"m19":{"validos":71805,"tarjetas":136036,"blanco":0.3041,"nulo":0.0686,"nomarcado":0.0995,"logo":0.2729,"nep":10.9025},"m23":{"validos":91976,"tarjetas":161344,"blanco":0.2516,"nulo":0.0594,"nomarcado":0.1189,"logo":0.2266,"nep":9.865},"g19":"PARTIDO CAMBIO RADICAL","g23":"PACTO HISTORICO"}},"concejo":{"total":128659,"partidos":[{"n":"PACTO HISTORICO","v":16015,"s":0.1245,"logo":16015,"cands":0,"s19":0.0735,"ant":"Soacha Humana y Alternativa"},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":14413,"s":0.112,"logo":620,"cands":19,"s19":null,"ant":null},{"n":"COALICION - CONCEJO","v":10986,"s":0.0854,"logo":1017,"cands":18,"s19":0.1634,"ant":"La U + MIRA"},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":9928,"s":0.0772,"logo":986,"cands":15,"s19":0.0476,"ant":null},{"n":"PARTIDO CAMBIO RADICAL","v":9094,"s":0.0707,"logo":1028,"cands":10,"s19":0.1375,"ant":null},{"n":"PARTIDO ALIANZA VERDE","v":8130,"s":0.0632,"logo":1389,"cands":15,"s19":0.0994,"ant":null},{"n":"PARTIDO CENTRO DEMOCRÁTICO","v":8005,"s":0.0622,"logo":1909,"cands":13,"s19":0.1033,"ant":null},{"n":"COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES","v":7650,"s":0.0595,"logo":404,"cands":19,"s19":0.0329,"ant":"Colombia Justa Libres"},{"n":"PARTIDO LIBERAL COLOMBIANO","v":7438,"s":0.0578,"logo":1068,"cands":18,"s19":0.0745,"ant":null},{"n":"MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"","v":6567,"s":0.051,"logo":420,"cands":19,"s19":0.0483,"ant":null},{"n":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":6232,"s":0.0484,"logo":400,"cands":16,"s19":0.0537,"ant":"ADA"},{"n":"PARTIDO NUEVO LIBERALISMO","v":5360,"s":0.0417,"logo":2332,"cands":15,"s19":null,"ant":null},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":4493,"s":0.0349,"logo":530,"cands":18,"s19":0.0384,"ant":null},{"n":"INDEPENDIENTES","v":4451,"s":0.0346,"logo":242,"cands":16,"s19":null,"ant":null},{"n":"PARTIDO ALIANZA SOCIAL INDEPENDIENTE \"ASI\"","v":2752,"s":0.0214,"logo":234,"cands":17,"s19":null,"ant":null},{"n":"PARTIDO POLÍTICO CREEMOS","v":2230,"s":0.0173,"logo":174,"cands":8,"s19":null,"ant":null},{"n":"PARTIDO POLÍTICO DIGNIDAD & COMPROMISO","v":861,"s":0.0067,"logo":184,"cands":5,"s19":null,"ant":null},{"n":"PARTIDO POLÍTICO LA FUERZA DE LA PAZ","v":804,"s":0.0062,"logo":804,"cands":0,"s19":null,"ant":null},{"n":"PARTIDO LIGA GOBERNANTES ANTICORRUPCIÓN - LIGA","v":777,"s":0.006,"logo":160,"cands":12,"s19":null,"ant":null},{"n":"MOVIMIENTO POLITICO FUERZA CIUDADANA","v":734,"s":0.0057,"logo":311,"cands":5,"s19":null,"ant":null},{"n":"NUEVA FUERZA DEMOCRÁTICA","v":731,"s":0.0057,"logo":138,"cands":5,"s19":null,"ant":null},{"n":"MOVIMIENTO SALVACIÓN NACIONAL","v":666,"s":0.0052,"logo":104,"cands":3,"s19":null,"ant":null},{"n":"PARTIDO ECOLOGISTA COLOMBIANO","v":342,"s":0.0027,"logo":136,"cands":4,"s19":null,"ant":null}],"candidatos":[{"n":"JONNATHAN ANDRES VELA RODRIGUEZ","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":3061,"v19":1320,"np":64},{"n":"JAZMIN OLARTE GUAYAMBUCO","pt":"COALICION - CONCEJO","v":2422,"v19":2029,"np":62},{"n":"HERNAN DARIO SOTO VARON","pt":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":2345,"v19":738,"np":63},{"n":"JOEL DE LOS RIOS OCAMPO","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":2294,"v19":1345,"np":64},{"n":"TERRY MAURICIO BOGOTA LOPEZ","pt":"PARTIDO CAMBIO RADICAL","v":2263,"v19":2018,"np":64},{"n":"JUAN CARLOS ARIAS CANTE","pt":"COALICION - CONCEJO","v":2226,"v19":2409,"np":63},{"n":"NORBERTO CUENCA RIVERA","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":2173,"v19":1954,"np":62},{"n":"EDGAR CARDENAS GONZALEZ","pt":"MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"","v":1950,"v19":2189,"np":63},{"n":"CARLOS ALBERTO OSPINA DIAZ","pt":"PARTIDO LIBERAL COLOMBIANO","v":1774,"v19":2210,"np":61},{"n":"JAIME ULISES SEPULVEDA DUARTE","pt":"PARTIDO CAMBIO RADICAL","v":1737,"v19":1651,"np":62},{"n":"LUIS EDUARDO FIGUEROA GUIRAL","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1735,"v19":null,"np":62},{"n":"LADY TATIANA SANCHEZ LAVERDE","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1617,"v19":null,"np":64},{"n":"JOSE MARTIN PEÑUELA BELTRAN","pt":"PARTIDO CAMBIO RADICAL","v":1576,"v19":null,"np":61},{"n":"NICOLAS MARTINEZ LANDINEZ","pt":"COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES","v":1572,"v19":894,"np":62},{"n":"WILSON ANDRES RODRIGUEZ FONSECA","pt":"PARTIDO ALIANZA VERDE","v":1442,"v19":2039,"np":63},{"n":"RICARDO ANDRES JARAMILLO GUZMAN","pt":"COALICION - CONCEJO","v":1283,"v19":null,"np":63},{"n":"JAIRO ZAMBRANO SANCHEZ","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1278,"v19":1098,"np":56},{"n":"YBON YAZBLEIDY FLORIDO ALVAREZ","pt":"PARTIDO ALIANZA VERDE","v":1268,"v19":null,"np":63},{"n":"JUAN CARLOS NEMOCON SOLORZANO","pt":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":1245,"v19":null,"np":62},{"n":"WILSON FABIAN TIQUE HORTA","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1233,"v19":1058,"np":59},{"n":"ANA ISABEL ALBA ALARCON","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1147,"v19":null,"np":59},{"n":"WILLIAM MARTIN NIÑO COCUNUBO","pt":"COALICION - CONCEJO","v":1102,"v19":null,"np":61},{"n":"ALBERTO PLAZAS BALAGUERA","pt":"PARTIDO ALIANZA SOCIAL INDEPENDIENTE \"ASI\"","v":1093,"v19":1705,"np":58},{"n":"JOHAN STEVEN MUÑOZ CARDENAS","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1081,"v19":null,"np":56},{"n":"EIDA RUBY PACHECO ALVARADO","pt":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":1033,"v19":null,"np":56},{"n":"JULIAN FERNANDO ORTIZ ORTIZ","pt":"PARTIDO ALIANZA VERDE","v":1007,"v19":null,"np":54},{"n":"WHENDY CAMILA POVEDA ALARCON","pt":"MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"","v":1002,"v19":null,"np":58},{"n":"LUIS ANDRES MONROY PAEZ","pt":"COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES","v":946,"v19":1154,"np":58},{"n":"WILBER ANDRES GONZALEZ GUTIERREZ","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":842,"v19":null,"np":60},{"n":"JACKSON FERNANDO PEÑA CASTILLO","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":808,"v19":603,"np":58},{"n":"ARGEMIRO OVALLE SANTAMARIA","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":795,"v19":843,"np":57},{"n":"SANDRA PAOLA MONTOYA RUIZ","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":742,"v19":null,"np":61},{"n":"CIOMARA CARDONA SANTA","pt":"INDEPENDIENTES","v":736,"v19":null,"np":52},{"n":"CARLOS GODFREY MORA ESTRADA","pt":"MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"","v":718,"v19":455,"np":59},{"n":"WILLAM RODRIGUEZ GARCIA","pt":"COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES","v":697,"v19":null,"np":58},{"n":"JUAN PABLO ESTRADA JIMENEZ","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":692,"v19":null,"np":60},{"n":"ARCENIO DE JESUS PERALTA VALBUENA","pt":"COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES","v":673,"v19":681,"np":55},{"n":"CHARLES IRWINN MORRIS REYES","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":634,"v19":null,"np":58},{"n":"ARCADIO CARVAJAL BERNAL","pt":"PARTIDO LIBERAL COLOMBIANO","v":614,"v19":572,"np":58},{"n":"ANGEL ALBERTO HERRERA RODRIGUEZ","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":613,"v19":null,"np":54}],"puestos":[{"n":"I.E. COMPARTIR","c":"Comuna 1","t":4889,"top":[["PACTO HISTORICO",520],["COALICION - CONCEJO",506],["AGRUPACIÓN POLÍTICA EN MARCHA",428]]},{"n":"I.E. GENERAL SANTANDER","c":"Comuna 2","t":4804,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",686],["PACTO HISTORICO",482],["PARTIDO CONSERVADOR COLOMBIANO",438]]},{"n":"I.E. INTEGRADO DE SOACHA","c":"Comuna 2","t":4677,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",647],["PACTO HISTORICO",616],["COALICION - CONCEJO",403]]},{"n":"I.E. LAS VILLAS- SEDE BARON DEL SOL","c":"Comuna 6","t":4580,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",569],["PACTO HISTORICO",496],["PARTIDO CONSERVADOR COLOMBIANO",388]]},{"n":"I.E. SAN MATEO SEDE A","c":"Comuna 5","t":4495,"top":[["PACTO HISTORICO",705],["COALICION - CONCEJO",596],["AGRUPACIÓN POLÍTICA EN MARCHA",380]]},{"n":"I.E. SOL NACIENTE","c":"Comuna 6","t":4187,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",527],["PARTIDO CONSERVADOR COLOMBIANO",445],["PACTO HISTORICO",417]]},{"n":"I.E. LEON XIII - CHILOE","c":"Comuna 3","t":4182,"top":[["PACTO HISTORICO",830],["PARTIDO ALIANZA VERDE",420],["PARTIDO CENTRO DEMOCRÁTICO",363]]},{"n":"CENTRO COMERCIAL GRAN PLAZA","c":"Comuna 3","t":4072,"top":[["PACTO HISTORICO",602],["COALICION - CONCEJO",400],["AGRUPACIÓN POLÍTICA EN MARCHA",388]]},{"n":"I.E. EL BOSQUE","c":"Comuna 5","t":4042,"top":[["PACTO HISTORICO",590],["COALICION - CONCEJO",563],["PARTIDO CENTRO DEMOCRÁTICO",441]]},{"n":"I.E. COMPARTIR PRIMARIA","c":"Comuna 1","t":3832,"top":[["COALICION - CONCEJO",415],["PACTO HISTORICO",398],["AGRUPACIÓN POLÍTICA EN MARCHA",314]]},{"n":"I.E. CIUDAD LATINA","c":"Comuna 1","t":3701,"top":[["PACTO HISTORICO",494],["AGRUPACIÓN POLÍTICA EN MARCHA",470],["MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"",400]]},{"n":"COLISEO LEON XIII","c":"Comuna 3","t":3542,"top":[["PACTO HISTORICO",499],["PARTIDO ALIANZA VERDE",457],["PARTIDO CAMBIO RADICAL",444]]},{"n":"COLISEO GENERAL SANTANDER","c":"Comuna 2","t":3500,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",550],["PACTO HISTORICO",303],["PARTIDO CONSERVADOR COLOMBIANO",300]]},{"n":"I. E. SANTA ANA - ANTONIO NARIÑO","c":"Comuna 1","t":3401,"top":[["PARTIDO CAMBIO RADICAL",328],["PACTO HISTORICO",302],["AGRUPACIÓN POLÍTICA EN MARCHA",301]]},{"n":"I.E. LEON XIII","c":"Comuna 3","t":3396,"top":[["PARTIDO ALIANZA VERDE",483],["PARTIDO CAMBIO RADICAL",407],["PARTIDO CONSERVADOR COLOMBIANO",357]]},{"n":"I.E. SOACHA AVANZA LA UNIDAD","c":"Comuna 3","t":3217,"top":[["PARTIDO ALIANZA VERDE",519],["PACTO HISTORICO",508],["PARTIDO CENTRO DEMOCRÁTICO",241]]},{"n":"I.E. SAN MATEO SEDE B","c":"Comuna 5","t":3054,"top":[["PACTO HISTORICO",437],["COALICION - CONCEJO",409],["AGRUPACIÓN POLÍTICA EN MARCHA",271]]},{"n":"I.E. CIUDADELA SUCRE","c":"Comuna 4","t":2888,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",613],["PARTIDO CENTRO DEMOCRÁTICO",421],["PACTO HISTORICO",253]]},{"n":"I.E. LICEO MAYOR DE SOACHA","c":"Comuna 5","t":2733,"top":[["PACTO HISTORICO",489],["PARTIDO CENTRO DEMOCRÁTICO",366],["COALICION - CONCEJO",253]]},{"n":"CONCENTRACION CAMILO TORRES","c":"Comuna 2","t":2699,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",395],["PARTIDO CONSERVADOR COLOMBIANO",291],["PARTIDO CAMBIO RADICAL",273]]},{"n":"I E JULIO CESAR TURBAY AYALA","c":"Comuna 4","t":2570,"top":[["PACTO HISTORICO",364],["AGRUPACIÓN POLÍTICA EN MARCHA",272],["COALICION - CONCEJO",217]]},{"n":"IE GENERAL SANTANDER SD MI TIERNA EDAD","c":"Comuna 2","t":2480,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",354],["PACTO HISTORICO",279],["PARTIDO CAMBIO RADICAL",192]]},{"n":"CENTRO COMERCIAL VENTURA TERREROS","c":"Comuna 5","t":2472,"top":[["PACTO HISTORICO",308],["AGRUPACIÓN POLÍTICA EN MARCHA",247],["COALICION - CONCEJO",246]]},{"n":"UNIVER. DE CUNDINAMARCA EXTENSION SOACHA","c":"Comuna 2","t":2444,"top":[["PACTO HISTORICO",420],["AGRUPACIÓN POLÍTICA EN MARCHA",268],["PARTIDO NUEVO LIBERALISMO",163]]},{"n":"COLEGIO BOLIVAR PRIMARIA","c":"Sin asignar","t":2380,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",342],["PACTO HISTORICO",253],["PARTIDO CONSERVADOR COLOMBIANO",225]]},{"n":"I E EDUARDO SANTOS SEDE PANAMERICANA","c":"Comuna 6","t":2247,"top":[["PARTIDO CAMBIO RADICAL",443],["PARTIDO LIBERAL COLOMBIANO",241],["AGRUPACIÓN POLÍTICA EN MARCHA",241]]},{"n":"I.E. SAN MATEO - MARISCAL SUCRE","c":"Comuna 6","t":2198,"top":[["PACTO HISTORICO",315],["PARTIDO LIBERAL COLOMBIANO",232],["COALICION - CONCEJO",218]]},{"n":"I.E. LA DESPENSA - CIUDAD VERDE","c":"Comuna 3","t":2197,"top":[["PACTO HISTORICO",408],["PARTIDO ALIANZA VERDE",284],["PARTIDO CENTRO DEMOCRÁTICO",164]]},{"n":"I.E. LAS VILLAS - SEDE LIBERTADORES","c":"Comuna 6","t":2187,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",314],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",226],["PACTO HISTORICO",209]]},{"n":"SALON COMUNAL CIUDAD SATELITE","c":"Comuna 2","t":2076,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",251],["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",220],["PACTO HISTORICO",204]]},{"n":"I.E. VIDA NUEVA","c":"Comuna 2","t":2059,"top":[["PACTO HISTORICO",348],["COALICION - CONCEJO",203],["PARTIDO CONSERVADOR COLOMBIANO",168]]},{"n":"CONCENTRACION ESCOLAR SAN NICOLAS","c":"Comuna 1","t":2038,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",479],["PACTO HISTORICO",239],["COALICION - CONCEJO",174]]},{"n":"COLEGIO MILITAR ALMIRANTE PADILLA","c":"Comuna 1","t":1966,"top":[["PARTIDO CAMBIO RADICAL",221],["PACTO HISTORICO",215],["COALICION - CONCEJO",202]]},{"n":"ESCUE NORMAL SUPERIOR MARIA AUXILIADORA","c":"Comuna 2","t":1819,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",266],["PACTO HISTORICO",232],["COALICION - CONCEJO",163]]},{"n":"COLEGIO MINUTO DE DIOS CIUDAD VERDE","c":"Comuna 3","t":1760,"top":[["PACTO HISTORICO",273],["PARTIDO ALIANZA VERDE",214],["AGRUPACIÓN POLÍTICA EN MARCHA",156]]},{"n":"CENTRO COMERCIAL MERCURIO","c":"Comuna 3","t":1716,"top":[["PACTO HISTORICO",257],["AGRUPACIÓN POLÍTICA EN MARCHA",196],["PARTIDO CONSERVADOR COLOMBIANO",160]]},{"n":"COLEGIO MILITAR LICEO SOCIAL COMPARTIR","c":"Comuna 1","t":1570,"top":[["PACTO HISTORICO",187],["AGRUPACIÓN POLÍTICA EN MARCHA",178],["COALICION - CONCEJO",126]]},{"n":"IE. NUEVO COMPARTIR","c":"Comuna 1","t":1411,"top":[["PACTO HISTORICO",191],["MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"",152],["PARTIDO CONSERVADOR COLOMBIANO",144]]},{"n":"CDI JARDIN SOCIAL SOL Y LUNA","c":"Comuna 2","t":1173,"top":[["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",224],["AGRUPACIÓN POLÍTICA EN MARCHA",180],["PACTO HISTORICO",115]]},{"n":"I.E. LA ISLA","c":"Comuna 4","t":968,"top":[["PARTIDO CENTRO DEMOCRÁTICO",161],["AGRUPACIÓN POLÍTICA EN MARCHA",130],["COALICION - CONCEJO",126]]},{"n":"I E GENERAL SANTANDER SEDE LA VEREDITA","c":"Comuna 2","t":961,"top":[["PACTO HISTORICO",135],["PARTIDO CONSERVADOR COLOMBIANO",118],["AGRUPACIÓN POLÍTICA EN MARCHA",90]]},{"n":"I.E. PAZ Y ESPERANZA","c":"Comuna 1","t":837,"top":[["PACTO HISTORICO",99],["PARTIDO NUEVO LIBERALISMO",86],["MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"",82]]},{"n":"CENTRO DE DESARROLLO INFANTIL COMPENSAR","c":"Comuna 2","t":825,"top":[["COALICION - CONCEJO",109],["PACTO HISTORICO",106],["AGRUPACIÓN POLÍTICA EN MARCHA",68]]},{"n":"I.E. MANUELA BELTRAN","c":"Comuna 3","t":770,"top":[["PACTO HISTORICO",112],["AGRUPACIÓN POLÍTICA EN MARCHA",84],["PARTIDO CONSERVADOR COLOMBIANO",81]]},{"n":"I.E. LA DESPENSA","c":"Comuna 3","t":767,"top":[["PACTO HISTORICO",100],["AGRUPACIÓN POLÍTICA EN MARCHA",76],["PARTIDO CONSERVADOR COLOMBIANO",74]]},{"n":"I.E. LUIS CARLOS GALAN","c":"Comuna 4","t":736,"top":[["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",122],["AGRUPACIÓN POLÍTICA EN MARCHA",108],["PACTO HISTORICO",78]]},{"n":"LICEO CRISTIANO VIDA NUEVA","c":"Comuna 6","t":719,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",98],["COALICION - CONCEJO",95],["PACTO HISTORICO",70]]},{"n":"CENTRO CIVICO DEPORTIVO SOACHA","c":"Comuna 5","t":714,"top":[["PACTO HISTORICO",85],["COALICION - CONCEJO",84],["AGRUPACIÓN POLÍTICA EN MARCHA",76]]},{"n":"COLEGIO COLSUBSIDIO - MAIPORE","c":"Comuna 1","t":688,"top":[["PACTO HISTORICO",116],["PARTIDO NUEVO LIBERALISMO",65],["PARTIDO LIBERAL COLOMBIANO",58]]},{"n":"COLEGIO COOPERATIVO EUGENIO DIAZ CASTRO","c":"Comuna 2","t":678,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",114],["COALICION - CONCEJO",75],["PARTIDO CAMBIO RADICAL",61]]},{"n":"I. E. EUGENIO DIAZ CASTRO SEDE PRIMARIA","c":"Corregimiento 2","t":656,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",238],["PACTO HISTORICO",70],["PARTIDO CAMBIO RADICAL",69]]},{"n":"IE LUIS HENRIQUEZ","c":"Comuna 2","t":558,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",62],["COALICION - CONCEJO",56],["PACTO HISTORICO",53]]},{"n":"SALON COMUNAL VILLA ITALIA","c":"Comuna 1","t":452,"top":[["PACTO HISTORICO",93],["COALICION - CONCEJO",84],["PARTIDO CONSERVADOR COLOMBIANO",30]]},{"n":"IE EDUARDO SANTOS","c":"Comuna 6","t":415,"top":[["PARTIDO CAMBIO RADICAL",63],["AGRUPACIÓN POLÍTICA EN MARCHA",50],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",46]]},{"n":"I. E. EUGENIO DIAZ CASTRO SAN JORGE","c":"Corregimiento 1","t":413,"top":[["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",214],["AGRUPACIÓN POLÍTICA EN MARCHA",47],["PARTIDO LIBERAL COLOMBIANO",33]]},{"n":"I. E. GABRIEL GARCIA MARQUEZ","c":"Comuna 4","t":385,"top":[["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",112],["PACTO HISTORICO",58],["AGRUPACIÓN POLÍTICA EN MARCHA",31]]},{"n":"SALON COMUNAL ALTOS DE LA FLORIDA","c":"Comuna 6","t":381,"top":[["PARTIDO LIBERAL COLOMBIANO",62],["PARTIDO CAMBIO RADICAL",55],["AGRUPACIÓN POLÍTICA EN MARCHA",41]]},{"n":"I.E. SOACHA PARA VIVIR MEJOR","c":"Comuna 6","t":341,"top":[["PARTIDO CAMBIO RADICAL",52],["AGRUPACIÓN POLÍTICA EN MARCHA",44],["PARTIDO LIBERAL COLOMBIANO",41]]},{"n":"IE BUENOS AIRES SEDE A","c":"Comuna 4","t":339,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",94],["PARTIDO CENTRO DEMOCRÁTICO",39],["COALICION - CONCEJO",29]]},{"n":"I.E. LA DESPENSA - MARCO FIDEL SUAREZ","c":"Comuna 3","t":296,"top":[["PARTIDO CONSERVADOR COLOMBIANO",46],["PARTIDO CAMBIO RADICAL",44],["PARTIDO ALIANZA VERDE",39]]},{"n":"BIBLIOTECA MUNICIPAL LA ISLA","c":"Comuna 4","t":295,"top":[["PARTIDO CENTRO DEMOCRÁTICO",56],["COALICION - CONCEJO",45],["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",28]]},{"n":"IE LUIS C. GALAN-SD VILLAS DE CASALOMA","c":"Comuna 4","t":223,"top":[["PACTO HISTORICO",42],["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",38],["PARTIDO CENTRO DEMOCRÁTICO",22]]},{"n":"I. E. EUGENIO DIAZ CASTRO SEDE CHACUA","c":"Corregimiento 1","t":221,"top":[["PARTIDO LIBERAL COLOMBIANO",162],["AGRUPACIÓN POLÍTICA EN MARCHA",12],["PACTO HISTORICO",7]]},{"n":"SALON COMUNAL VEREDA FUSUNGA","c":"Corregimiento 1","t":207,"top":[["AGRUPACIÓN POLÍTICA EN MARCHA",55],["PARTIDO LIBERAL COLOMBIANO",50],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",39]]},{"n":"IE BENEDICTO XVI","c":"Comuna 3","t":160,"top":[["PARTIDO ALIANZA VERDE",25],["PARTIDO CAMBIO RADICAL",22],["AGRUPACIÓN POLÍTICA EN MARCHA",18]]}],"por_comuna":{"Comuna 1":[["PACTO HISTORICO",2854],["AGRUPACIÓN POLÍTICA EN MARCHA",2566],["COALICION - CONCEJO",2286],["MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"",1837],["PARTIDO CONSERVADOR COLOMBIANO",1776],["PARTIDO CAMBIO RADICAL",1691],["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",1587],["INDEPENDIENTES",1386],["__total",24785]],"Comuna 2":[["AGRUPACIÓN POLÍTICA EN MARCHA",4074],["PACTO HISTORICO",3543],["PARTIDO CONSERVADOR COLOMBIANO",2491],["COALICION - CONCEJO",2358],["PARTIDO CAMBIO RADICAL",2060],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",2000],["PARTIDO CENTRO DEMOCRÁTICO",1657],["MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"",1585],["__total",30753]],"Comuna 3":[["PACTO HISTORICO",3970],["PARTIDO ALIANZA VERDE",2972],["AGRUPACIÓN POLÍTICA EN MARCHA",2152],["PARTIDO CAMBIO RADICAL",2104],["PARTIDO CONSERVADOR COLOMBIANO",2097],["COALICION - CONCEJO",2012],["PARTIDO CENTRO DEMOCRÁTICO",1750],["PARTIDO NUEVO LIBERALISMO",1371],["__total",26075]],"Comuna 4":[["AGRUPACIÓN POLÍTICA EN MARCHA",1282],["PARTIDO CENTRO DEMOCRÁTICO",942],["PACTO HISTORICO",902],["COALICION - CONCEJO",728],["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",700],["PARTIDO LIBERAL COLOMBIANO",594],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",489],["PARTIDO CONSERVADOR COLOMBIANO",465],["__total",8404]],"Comuna 5":[["PACTO HISTORICO",2614],["COALICION - CONCEJO",2151],["PARTIDO CENTRO DEMOCRÁTICO",1600],["AGRUPACIÓN POLÍTICA EN MARCHA",1556],["PARTIDO CONSERVADOR COLOMBIANO",1298],["PARTIDO LIBERAL COLOMBIANO",1123],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",1037],["PARTIDO ALIANZA VERDE",1005],["__total",17510]],"Comuna 6":[["AGRUPACIÓN POLÍTICA EN MARCHA",2089],["PACTO HISTORICO",1791],["PARTIDO CAMBIO RADICAL",1673],["PARTIDO CONSERVADOR COLOMBIANO",1487],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",1366],["PARTIDO LIBERAL COLOMBIANO",1272],["COALICION - CONCEJO",1261],["PARTIDO ALIANZA VERDE",868],["__total",17255]],"Sin asignar":[["AGRUPACIÓN POLÍTICA EN MARCHA",342],["PACTO HISTORICO",253],["PARTIDO CONSERVADOR COLOMBIANO",225],["PARTIDO CAMBIO RADICAL",187],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",173],["COALICION - CONCEJO",146],["PARTIDO ALIANZA VERDE",130],["MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"",125],["__total",2380]],"Corregimiento 1":[["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",260],["PARTIDO LIBERAL COLOMBIANO",245],["AGRUPACIÓN POLÍTICA EN MARCHA",114],["MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"",31],["PARTIDO CAMBIO RADICAL",26],["PARTIDO CONSERVADOR COLOMBIANO",26],["PACTO HISTORICO",18],["PARTIDO CENTRO DEMOCRÁTICO",18],["__total",841]],"Corregimiento 2":[["AGRUPACIÓN POLÍTICA EN MARCHA",238],["PACTO HISTORICO",70],["PARTIDO CAMBIO RADICAL",69],["PARTIDO CONSERVADOR COLOMBIANO",63],["COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES",46],["COALICION - CONCEJO",29],["MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021",24],["MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"",23],["__total",656]]}},"jal":{"Comuna 3":{"total":19801,"puestos":["I.E. LA DESPENSA","COLEGIO MINUTO DE DIOS CIUDAD VERDE","IE BENEDICTO XVI","CENTRO COMERCIAL MERCURIO","I.E. MANUELA BELTRAN","I.E. LEON XIII","CENTRO COMERCIAL GRAN PLAZA","COLISEO LEON XIII","I.E. LA DESPENSA - CIUDAD VERDE","I.E. LEON XIII - CHILOE","I.E. LA DESPENSA - MARCO FIDEL SUAREZ","I.E. SOACHA AVANZA LA UNIDAD"],"partidos":[{"n":"PACTO HISTORICO","v":5198,"logo":1731,"cands":6},{"n":"PARTIDO ALIANZA VERDE","v":2220,"logo":538,"cands":5},{"n":"PARTIDO CENTRO DEMOCRÁTICO","v":2134,"logo":582,"cands":3},{"n":"PARTIDO NUEVO LIBERALISMO","v":2129,"logo":879,"cands":1},{"n":"COALICION U-MIRA","v":1719,"logo":246,"cands":7},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":1395,"logo":192,"cands":6},{"n":"PARTIDO CAMBIO RADICAL","v":1353,"logo":272,"cands":4},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1048,"logo":193,"cands":4},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":863,"logo":134,"cands":6},{"n":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":746,"logo":78,"cands":5},{"n":"MOVIMIENTO POLITICO FUERZA CIUDADANA","v":361,"logo":113,"cands":3},{"n":"INDEPENDIENTES","v":323,"logo":47,"cands":4},{"n":"PARTIDO POLÍTICO DIGNIDAD & COMPROMISO","v":312,"logo":62,"cands":2}],"candidatos":[{"n":"SANDRA CATALINA SANCHEZ GONZALEZ","pt":"PARTIDO NUEVO LIBERALISMO","v":1250,"v19":null},{"n":"JOSE ALCIDES ALBA LAVERDE","pt":"PACTO HISTORICO","v":1037,"v19":251},{"n":"ALFONSO AMILCAR VELASQUEZ AGUILERA","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":836,"v19":null},{"n":"WALTER ALEXI ARIZA SARMIENTO","pt":"PACTO HISTORICO","v":653,"v19":159},{"n":"JONATHAN ALBEIRO CIFUENTES LOPEZ","pt":"PARTIDO ALIANZA VERDE","v":616,"v19":null},{"n":"SAUL VILLATE MORENO","pt":"PACTO HISTORICO","v":592,"v19":null},{"n":"ERICK SANTIAGO MEDINA VANEGAS","pt":"COALICION U-MIRA","v":587,"v19":null},{"n":"ELISABETH PIMENTEL PERDOMO","pt":"PACTO HISTORICO","v":484,"v19":null},{"n":"LUZ ESTRELLA HERNANDEZ RIVEROS","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":472,"v19":null},{"n":"MARIO PALACIOS","pt":"PARTIDO CAMBIO RADICAL","v":418,"v19":null},{"n":"LUIS MIGUEL AVENDAÑO CHAPARRO","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":391,"v19":null},{"n":"CLAUDIA ERNESTINA VARGAS GODOY","pt":"PACTO HISTORICO","v":366,"v19":null}]},"Comuna 2":{"total":20132,"puestos":["I.E. GENERAL SANTANDER","I.E. VIDA NUEVA","CDI JARDIN SOCIAL SOL Y LUNA","ESCUE NORMAL SUPERIOR MARIA AUXILIADORA","IE LUIS HENRIQUEZ","COLEGIO COOPERATIVO EUGENIO DIAZ CASTRO","IE GENERAL SANTANDER SD MI TIERNA EDAD","I.E. INTEGRADO DE SOACHA","COLISEO GENERAL SANTANDER","CONCENTRACION CAMILO TORRES","I E GENERAL SANTANDER SEDE LA VEREDITA","SALON COMUNAL CIUDAD SATELITE","UNIVER. DE CUNDINAMARCA EXTENSION SOACHA","CENTRO DE DESARROLLO INFANTIL COMPENSAR"],"partidos":[{"n":"PACTO HISTORICO","v":5572,"logo":1535,"cands":7},{"n":"PARTIDO CENTRO DEMOCRÁTICO","v":2011,"logo":524,"cands":2},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1995,"logo":248,"cands":7},{"n":"PARTIDO CAMBIO RADICAL","v":1851,"logo":267,"cands":6},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":1428,"logo":199,"cands":6},{"n":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":1331,"logo":148,"cands":7},{"n":"PARTIDO DE LA UNIÓN POR LA GENTE - PARTIDO DE LA U","v":1101,"logo":153,"cands":6},{"n":"INDEPENDIENTES","v":1000,"logo":126,"cands":7},{"n":"PARTIDO DEMÓCRATA COLOMBIANO","v":967,"logo":115,"cands":7},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":917,"logo":151,"cands":4},{"n":"MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"","v":834,"logo":260,"cands":1},{"n":"PARTIDO POLÍTICO CREEMOS","v":397,"logo":74,"cands":3},{"n":"PARTIDO POLÍTICO DIGNIDAD & COMPROMISO","v":254,"logo":57,"cands":3},{"n":"PARTIDO POLÍTICO LA FUERZA DE LA PAZ","v":248,"logo":248,"cands":0},{"n":"PARTIDO ECOLOGISTA COLOMBIANO","v":226,"logo":64,"cands":3}],"candidatos":[{"n":"SEBASTIAN CRUZ PARRA","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":980,"v19":null},{"n":"HECTOR JAVIER REY MICAN","pt":"PACTO HISTORICO","v":923,"v19":null},{"n":"DANIELA CRUZ PARRA","pt":"PACTO HISTORICO","v":670,"v19":null},{"n":"KEVIN ALEXANDER MARTINEZ TORO","pt":"PACTO HISTORICO","v":660,"v19":null},{"n":"MARCO AURELIO CAICEDO BELLO","pt":"PACTO HISTORICO","v":574,"v19":208},{"n":"FERNANDO MORA ESCOBAR","pt":"MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"","v":574,"v19":null},{"n":"CLAUDIA PATRICIA FERREIRA PINEDA","pt":"PACTO HISTORICO","v":530,"v19":null},{"n":"NIDIA ESPERANZA CORDOBA CORDOBA","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":507,"v19":null},{"n":"DANIELA MILENA ABRIL AYALA","pt":"PARTIDO CAMBIO RADICAL","v":485,"v19":null},{"n":"ROSALBA SUAREZ RUBIO","pt":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":467,"v19":null},{"n":"CLAUDIA MARTHA GONZALEZ TIQUE","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":447,"v19":null},{"n":"PAULA STEFANY GOMEZ CORREA","pt":"PACTO HISTORICO","v":404,"v19":null}]},"Comuna 1":{"total":19050,"puestos":["I. E. SANTA ANA - ANTONIO NARIÑO","SALON COMUNAL VILLA ITALIA","COLEGIO MILITAR LICEO SOCIAL COMPARTIR","I.E. COMPARTIR","I.E. CIUDAD LATINA","IE. NUEVO COMPARTIR","CONCENTRACION ESCOLAR SAN NICOLAS","I.E. COMPARTIR PRIMARIA","COLEGIO MILITAR ALMIRANTE PADILLA","COLEGIO COLSUBSIDIO - MAIPORE","I.E. PAZ Y ESPERANZA"],"partidos":[{"n":"PACTO HISTORICO","v":3825,"logo":1182,"cands":7},{"n":"PARTIDO NUEVO LIBERALISMO","v":2013,"logo":619,"cands":3},{"n":"COALICION U MIRA","v":1925,"logo":281,"cands":6},{"n":"PARTIDO CAMBIO RADICAL","v":1562,"logo":291,"cands":7},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":1492,"logo":198,"cands":6},{"n":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":1247,"logo":148,"cands":7},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":1070,"logo":151,"cands":6},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":1067,"logo":150,"cands":7},{"n":"PARTIDO ALIANZA VERDE","v":1047,"logo":330,"cands":3},{"n":"MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA \"AICO\"","v":932,"logo":199,"cands":4},{"n":"INDEPENDIENTES","v":918,"logo":100,"cands":7},{"n":"PARTIDO DEMÓCRATA COLOMBIANO","v":779,"logo":66,"cands":6},{"n":"PARTIDO POLÍTICO CREEMOS","v":431,"logo":62,"cands":3},{"n":"PARTIDO POLÍTICO LA FUERZA DE LA PAZ","v":287,"logo":50,"cands":2},{"n":"MOVIMIENTO POLITICO FUERZA CIUDADANA","v":241,"logo":63,"cands":2},{"n":"PARTIDO POLÍTICO DIGNIDAD & COMPROMISO","v":214,"logo":35,"cands":3}],"candidatos":[{"n":"RUBEN ALEXANDER GIRALDO BENAVIDES","pt":"COALICION U MIRA","v":772,"v19":null},{"n":"LEIDY LAURA ISRRAEL PALACIO","pt":"PACTO HISTORICO","v":743,"v19":null},{"n":"MANUEL JESUS LOPEZ","pt":"PARTIDO NUEVO LIBERALISMO","v":633,"v19":318},{"n":"JEFFREY STUART SANCHEZ ALVARADO","pt":"PARTIDO NUEVO LIBERALISMO","v":546,"v19":null},{"n":"NELCY MONTAÑA GARCIA","pt":"PACTO HISTORICO","v":470,"v19":null},{"n":"BRAYAN STEVEN BUITRAGO HENAO","pt":"PACTO HISTORICO","v":374,"v19":null},{"n":"ADRIANA CARDONA GARCIA","pt":"COALICION U MIRA","v":363,"v19":338},{"n":"JHON ANDRES ABREU VALBUENA","pt":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":316,"v19":187},{"n":"CLAUDIA MARCELA FORERO","pt":"PARTIDO ALIANZA VERDE","v":315,"v19":null},{"n":"MARTHA CONSUELO MACANA GONZALEZ","pt":"PACTO HISTORICO","v":300,"v19":null},{"n":"JOSE ROJAS CARREÑO","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":300,"v19":null},{"n":"FABIAN ANDRES TORRES","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":300,"v19":null}]},"Comuna 5":{"total":12693,"puestos":["CENTRO COMERCIAL VENTURA TERREROS","I.E. EL BOSQUE","I.E. SAN MATEO SEDE A","I.E. SAN MATEO SEDE B","I.E. LICEO MAYOR DE SOACHA","CENTRO CIVICO DEPORTIVO SOACHA"],"partidos":[{"n":"PACTO HISTORICO","v":3692,"logo":1113,"cands":6},{"n":"PARTIDO CENTRO DEMOCRÁTICO","v":1650,"logo":308,"cands":5},{"n":"PARTIDO DE LA UNIÓN POR LA GENTE - PARTIDO DE LA U","v":1140,"logo":120,"cands":7},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":1097,"logo":91,"cands":7},{"n":"PARTIDO NUEVO LIBERALISMO","v":1009,"logo":441,"cands":1},{"n":"PARTIDO LIBERAL COLOMBIANO","v":754,"logo":143,"cands":3},{"n":"PARTIDO ALIANZA VERDE","v":712,"logo":247,"cands":1},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":638,"logo":96,"cands":5},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":508,"logo":82,"cands":4},{"n":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":470,"logo":60,"cands":6},{"n":"PARTIDO CAMBIO RADICAL","v":425,"logo":138,"cands":1},{"n":"PARTIDO POLÍTICO LA FUERZA DE LA PAZ","v":292,"logo":0,"cands":3},{"n":"MOVIMIENTO POLITICO FUERZA CIUDADANA","v":161,"logo":47,"cands":2},{"n":"PARTIDO POLÍTICO DIGNIDAD & COMPROMISO","v":145,"logo":35,"cands":2}],"candidatos":[{"n":"KAREN ALEJANDRA ECHEVERRY MORENO","pt":"PACTO HISTORICO","v":815,"v19":null},{"n":"MIGUEL ANGEL JARAMILLO ALVAREZ","pt":"PARTIDO NUEVO LIBERALISMO","v":568,"v19":null},{"n":"LILIANA PATRICIA PARRA DIAZ","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":496,"v19":298},{"n":"ANA CAROLINA ORDOÑEZ SAENZ","pt":"PARTIDO ALIANZA VERDE","v":465,"v19":null},{"n":"JUAN DIEGO TUNJO PINILLA","pt":"PACTO HISTORICO","v":462,"v19":null},{"n":"EDNA VIVIANA MACANA BARRERA","pt":"PACTO HISTORICO","v":438,"v19":null},{"n":"ELIAN ANDRES GUIZA AYALA","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":337,"v19":null},{"n":"EUGENIO RODRIGUEZ LIEVANO","pt":"PACTO HISTORICO","v":336,"v19":null},{"n":"JEREMIAS MORALES BARRETO","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":300,"v19":233},{"n":"SONIA DEL PILAR OROZCO RICO","pt":"PARTIDO CAMBIO RADICAL","v":287,"v19":null},{"n":"EDGAR HERNAN NIÑO","pt":"PARTIDO LIBERAL COLOMBIANO","v":275,"v19":282},{"n":"LUIS ALBERTO RINCON POVEDA","pt":"PACTO HISTORICO","v":265,"v19":null}]},"Comuna 6":{"total":12052,"puestos":["I.E. LAS VILLAS- SEDE BARON DEL SOL","I.E. LAS VILLAS - SEDE LIBERTADORES","I.E. SOL NACIENTE","I.E. SAN MATEO - MARISCAL SUCRE","I E EDUARDO SANTOS SEDE PANAMERICANA","I.E. SOACHA PARA VIVIR MEJOR","SALON COMUNAL ALTOS DE LA FLORIDA","LICEO CRISTIANO VIDA NUEVA","IE EDUARDO SANTOS"],"partidos":[{"n":"PACTO HISTORICO","v":2751,"logo":754,"cands":7},{"n":"PARTIDO CAMBIO RADICAL","v":1300,"logo":165,"cands":6},{"n":"COALICION U MIRA","v":1016,"logo":131,"cands":6},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":946,"logo":137,"cands":5},{"n":"PARTIDO DEMÓCRATA COLOMBIANO","v":824,"logo":69,"cands":7},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":791,"logo":107,"cands":5},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":690,"logo":94,"cands":4},{"n":"PARTIDO LIBERAL COLOMBIANO","v":669,"logo":161,"cands":3},{"n":"PARTIDO NUEVO LIBERALISMO","v":660,"logo":265,"cands":1},{"n":"PARTIDO CENTRO DEMOCRÁTICO","v":646,"logo":646,"cands":0},{"n":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":597,"logo":77,"cands":5},{"n":"PARTIDO ALIANZA VERDE","v":487,"logo":123,"cands":4},{"n":"MOVIMIENTO POLITICO FUERZA CIUDADANA","v":201,"logo":40,"cands":3},{"n":"PARTIDO POLÍTICO LA FUERZA DE LA PAZ","v":195,"logo":61,"cands":1},{"n":"PARTIDO ECOLOGISTA COLOMBIANO","v":146,"logo":0,"cands":2},{"n":"PARTIDO POLÍTICO DIGNIDAD & COMPROMISO","v":133,"logo":0,"cands":2}],"candidatos":[{"n":"LEIDY VIVIANA BUITRAGO DIAZ","pt":"PACTO HISTORICO","v":497,"v19":null},{"n":"ALEXANDER ALARCON CORDOBA","pt":"PARTIDO NUEVO LIBERALISMO","v":395,"v19":null},{"n":"JOSE RAMON SEGURA BENALCAZAR","pt":"PACTO HISTORICO","v":369,"v19":null},{"n":"ALEXIS ECHEVERRI GARCIA","pt":"PACTO HISTORICO","v":305,"v19":null},{"n":"OSBALDO OROZCO GARCIA","pt":"PARTIDO CAMBIO RADICAL","v":289,"v19":null},{"n":"RODOLFO CORTES CONTRERAS","pt":"PARTIDO CAMBIO RADICAL","v":265,"v19":233},{"n":"GERSON WALDYR CAÑON GUTIERREZ","pt":"PACTO HISTORICO","v":253,"v19":null},{"n":"JOHN IVAN RUIZ JIMENEZ","pt":"PARTIDO LIBERAL COLOMBIANO","v":251,"v19":null},{"n":"YOMER NUÑEZ DUEÑAS","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":250,"v19":null},{"n":"MARIA CONSUELO SANCHEZ TRUJILLO","pt":"COALICION U MIRA","v":248,"v19":null},{"n":"MONICA ALEJANDRA PARRA SEGURA","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":236,"v19":null},{"n":"LIGIA PATIÑO ROSAS","pt":"PACTO HISTORICO","v":228,"v19":130}]},"Comuna 4":{"total":6644,"puestos":["I.E. LUIS CARLOS GALAN","I.E. CIUDADELA SUCRE","I.E. LA ISLA","I E JULIO CESAR TURBAY AYALA","I. E. GABRIEL GARCIA MARQUEZ","IE LUIS C. GALAN-SD VILLAS DE CASALOMA","BIBLIOTECA MUNICIPAL LA ISLA","IE BUENOS AIRES SEDE A"],"partidos":[{"n":"PACTO HISTORICO","v":1277,"logo":401,"cands":7},{"n":"PARTIDO CENTRO DEMOCRÁTICO","v":1109,"logo":246,"cands":4},{"n":"PARTIDO LIBERAL COLOMBIANO","v":676,"logo":102,"cands":6},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":577,"logo":92,"cands":5},{"n":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":563,"logo":59,"cands":6},{"n":"PARTIDO NUEVO LIBERALISMO","v":450,"logo":219,"cands":1},{"n":"PARTIDO CAMBIO RADICAL","v":432,"logo":82,"cands":4},{"n":"PARTIDO DE LA UNIÓN POR LA GENTE - PARTIDO DE LA U","v":405,"logo":82,"cands":6},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":404,"logo":67,"cands":3},{"n":"PARTIDO ALIANZA VERDE","v":295,"logo":137,"cands":1},{"n":"PARTIDO DEMÓCRATA COLOMBIANO","v":253,"logo":42,"cands":4},{"n":"MOVIMIENTO POLITICO FUERZA CIUDADANA","v":110,"logo":33,"cands":2},{"n":"INDEPENDIENTES","v":93,"logo":93,"cands":0}],"candidatos":[{"n":"DERLY PATRICIA RAMIREZ CIFUENTES","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":361,"v19":null},{"n":"MANUEL ADELMO VERGARA BERMUDEZ","pt":"PARTIDO NUEVO LIBERALISMO","v":231,"v19":140},{"n":"NORMA YANETH QUINTERO HERRERA","pt":"PACTO HISTORICO","v":209,"v19":null},{"n":"JUAN ESTICK DEVIA RUIZ","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":202,"v19":null},{"n":"MARIA TRINIDAD MONTENEGRO LEON","pt":"PACTO HISTORICO","v":195,"v19":null},{"n":"MARIA ELENA BASTO RAMOS","pt":"PARTIDO CENTRO DEMOCRÁTICO","v":187,"v19":248},{"n":"GUISELLA CASTRO GARCIA","pt":"MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021","v":179,"v19":null},{"n":"WILLAN JAVIER LEON ORTIZ","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":177,"v19":null},{"n":"SANDRA LILIANA CUPITRA","pt":"PACTO HISTORICO","v":170,"v19":null},{"n":"ELIANA MARCELA BOHORQUEZ LOPEZ","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":160,"v19":null},{"n":"LEONID BERNAL HERNANDEZ","pt":"PARTIDO ALIANZA VERDE","v":158,"v19":null},{"n":"PETRONA MOSQUERA CHAVERRA","pt":"PARTIDO LIBERAL COLOMBIANO","v":144,"v19":236}]},"Corregimiento 2":{"total":490,"puestos":["I. E. EUGENIO DIAZ CASTRO SEDE PRIMARIA"],"partidos":[{"n":"PARTIDO CAMBIO RADICAL","v":249,"logo":0,"cands":3},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":156,"logo":37,"cands":1},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":55,"logo":0,"cands":1},{"n":"PARTIDO DEMÓCRATA COLOMBIANO","v":30,"logo":0,"cands":1}],"candidatos":[{"n":"DIANA ANDREA AVILA RODRIGUEZ","pt":"PARTIDO CAMBIO RADICAL","v":167,"v19":90},{"n":"LIBIA HURTADO MURCIA","pt":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":119,"v19":null},{"n":"MIGUEL ANGEL CANGREJO MARQUEZ","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":55,"v19":null},{"n":"CARMENZA RAMIREZ HERRERA","pt":"PARTIDO CAMBIO RADICAL","v":50,"v19":38},{"n":"JUAN ALEXI BAEZ PEREZ","pt":"PARTIDO CAMBIO RADICAL","v":32,"v19":45},{"n":"ESNEIDER ORLANDO REY PARADA","pt":"PARTIDO DEMÓCRATA COLOMBIANO","v":30,"v19":null}]},"Corregimiento 1":{"total":503,"puestos":["I. E. EUGENIO DIAZ CASTRO SEDE CHACUA","I. E. EUGENIO DIAZ CASTRO SAN JORGE","SALON COMUNAL VEREDA FUSUNGA"],"partidos":[{"n":"PARTIDO LIBERAL COLOMBIANO","v":245,"logo":0,"cands":2},{"n":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":132,"logo":0,"cands":2},{"n":"AGRUPACIÓN POLÍTICA EN MARCHA","v":53,"logo":0,"cands":1},{"n":"INDEPENDIENTES","v":39,"logo":39,"cands":0},{"n":"PARTIDO CONSERVADOR COLOMBIANO","v":34,"logo":0,"cands":1}],"candidatos":[{"n":"NORBEY BELLO NAVARRETE","pt":"PARTIDO LIBERAL COLOMBIANO","v":128,"v19":76},{"n":"JOSE GIOVANY MORENO BECERRA","pt":"PARTIDO LIBERAL COLOMBIANO","v":117,"v19":54},{"n":"LUIS HUMBERTO BELLO TORRES","pt":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":69,"v19":34},{"n":"LUIS EMILIO RAMIREZ GONZALEZ","pt":"MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL \"MAIS\"","v":63,"v19":51},{"n":"LEIDY CAROLINA PINEDA TELLEZ","pt":"AGRUPACIÓN POLÍTICA EN MARCHA","v":53,"v19":null},{"n":"HAROLD LEANDRO MUNEVAR RAMIREZ","pt":"PARTIDO CONSERVADOR COLOMBIANO","v":34,"v19":null}]}},"asamblea":{"total":96030,"partidos":[["PACTO HISTÓRICO",21099],["PARTIDO ALIANZA VERDE",14585],["PARTIDO CAMBIO RADICAL",9466],["DEMÓCRATA, JUSTA LIBRES",9303],["COALICIÓN PARTIDO DE LA U - PARTIDO MIRA",9226],["CENTRO DEMOCRATICO Y SALVACION NACIONAL",7933],["PARTIDO LIBERAL COLOMBIANO - MAIS",7253],["PARTIDO CONSERVADOR COLOMBIANO",6620],["AGRUPACIÓN POLÍTICA EN MARCHA",4278],["ASI ES LA FUERZA DE LA PAZ EN CUNDINAMARCA",2460],["MOVIMIENTO POLITICO FUERZA CIUDADANA",1483],["PARTIDO VERDE OXÍGENO",941],["PARTIDO LIGA GOBERNANTES ANTICORRUPCIÓN - LIGA",711],["ATREVETE POR CUNDINAMARCA",672]]},"alcaldia":{"potencial":317080,"sufragantes":178029,"validos":168779,"blanco":14261,"nulos":6974,"nomarcados":2276,"cands":[["Víctor Julián Sánchez “Perico”","Partido de la U",62736],["Dany René Caicedo","Para Avanzar Más",53214],["Heiner de Jesús Gaitán","Pacto Histórico – Alianza Verde",19441],["Gloria Betty Zorro","Rescatemos a Soacha",14911],["Luis Alfonso Agudelo","Dignidad & Compromiso",1581],["Freddy Alexander González","Amor por Soacha",1080],["Camilo Andrés Nemocón","Suacha Diferente",708],["Mario Orlando Ballén","Salvación Nacional",324],["Jhon Yenifer González","Nueva Fuerza Democrática",304],["Jesús Ochoa Sánchez","Fuerza Ciudadana",219]]},"jal_blanco_ratio":0.4414,"concejo_blanco":25548};
  const CURULES_CONCEJO = 19;

  /* ---------- utilidades ---------- */
  const nf = new Intl.NumberFormat('es-CO');
  const fmt = n => nf.format(Math.round(n));
  const pct = (x, d = 1) => (x * 100).toLocaleString('es-CO', { minimumFractionDigits: d, maximumFractionDigits: d }) + ' %';
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const NOMBRES = {
    'PACTO HISTORICO': 'Pacto Histórico',
    'AGRUPACIÓN POLÍTICA EN MARCHA': 'En Marcha',
    'COALICION - CONCEJO': 'Coalición U – MIRA',
    'COALICION U MIRA': 'Coalición U – MIRA',
    'PARTIDO CONSERVADOR COLOMBIANO': 'Conservador',
    'PARTIDO CAMBIO RADICAL': 'Cambio Radical',
    'PARTIDO ALIANZA VERDE': 'Alianza Verde',
    'PARTIDO CENTRO DEMOCRÁTICO': 'Centro Democrático',
    'PARTIDO CENTRO DEMOCRATICO': 'Centro Democrático',
    'COALICION PARTIDO DEMOCRATA-COLOMBIA JUSTA LIBRES': 'Demócrata – Justa Libres',
    'PARTIDO LIBERAL COLOMBIANO': 'Liberal',
    'MOVIMIENTO AUTORIDADES INDÍGENAS DE COLOMBIA "AICO"': 'AICO',
    'MOVIMIENTO ALIANZA DEMOCRÁTICA AMPLIA - RES. 2049 DE 2021': 'ADA',
    'PARTIDO NUEVO LIBERALISMO': 'Nuevo Liberalismo',
    'MOVIMIENTO ALTERNATIVO INDÍGENA Y SOCIAL "MAIS"': 'MAIS',
    'PARTIDO DE LA UNIÓN POR LA GENTE - PARTIDO DE LA U': 'Partido de la U',
    'PARTIDO DEMÓCRATA COLOMBIANO': 'Demócrata Colombiano',
    'PARTIDO POLÍTICO DIGNIDAD & COMPROMISO': 'Dignidad & Compromiso',
    'INDEPENDIENTES': 'Independientes'
  };
  const tc = s => s.toLowerCase().replace(/(^|\s|-|“|")(\p{L})/gu, (m, a, b) => a + b.toUpperCase());
  const nom = n => NOMBRES[n] || tc(n.replace(/^PARTIDO (POLÍTICO |POLITICO )?/, '').replace(/^MOVIMIENTO /, 'Mov. ').replace(/"/g, ''));
  const persona = n => tc(n);

  /* Reparto de curules: cociente = (votos a listas + blanco) / curules; umbral = 50 % del cociente; cifra repartidora (D'Hondt) */
  function repartir(listas, blanco, curules) {
    const validos = listas.reduce((s, l) => s + l.v, 0) + blanco;
    const cociente = validos / curules;
    const umbral = cociente / 2;
    const habil = listas.filter(l => l.v >= umbral);
    const q = [];
    habil.forEach(l => { for (let k = 1; k <= curules; k++) q.push({ n: l.n, x: l.v / k }); });
    q.sort((a, b) => b.x - a.x);
    const ganadas = q.slice(0, curules);
    const seats = {};
    ganadas.forEach(g => { seats[g.n] = (seats[g.n] || 0) + 1; });
    const cifra = ganadas.length ? ganadas[ganadas.length - 1].x : 0;
    return { seats, cifra, cociente, umbral, validos };
  }

  /* ---------- estilos ---------- */
  const CSS = `
  #bt-root{--ink:#0F1C2E;--forest:#13273D;--forest2:#1E3A57;--gold:#C8A560;--gold-d:#A98841;--gold-s:#F4EDDA;--paper:#F4F6F9;--card:#fff;--line:#E2E8F0;--muted:#6B7A90;--soft:#F4F6F9;
    position:fixed;inset:0;z-index:9990;background:var(--paper);color:var(--ink);font-family:inherit;display:none;flex-direction:column;-webkit-font-smoothing:antialiased}
  #bt-root.bt-open{display:flex}
  #bt-root *{box-sizing:border-box}
  #bt-root button{font-family:inherit}
  #bt-root :focus-visible{outline:2px solid var(--gold);outline-offset:2px}
  .bt-top{background:var(--forest);color:#fff;padding:18px 32px 0;flex:none}
  .bt-top-row{display:flex;align-items:flex-start;justify-content:space-between;gap:24px}
  .bt-kicker{color:var(--gold);font-weight:600;font-size:14px;margin:0 0 4px}
  .bt-title{margin:0;font-size:30px;line-height:1.1;font-weight:800;letter-spacing:.01em}
  .bt-sub{margin:6px 0 0;color:#c9d1c8;font-size:14px}
  .bt-close{background:transparent;border:1px solid rgba(255,255,255,.28);color:#fff;border-radius:10px;padding:9px 16px;font-weight:600;cursor:pointer;font-size:14px}
  .bt-close:hover{border-color:var(--gold);color:var(--gold)}
  .bt-nav{display:flex;gap:4px;margin-top:18px;overflow-x:auto}
  .bt-nav button{background:transparent;border:0;color:#c9d1c8;padding:12px 18px;font-size:15px;font-weight:600;cursor:pointer;border-radius:10px 10px 0 0;white-space:nowrap}
  .bt-nav button:hover{color:#fff}
  .bt-nav button[aria-selected=true]{background:var(--paper);color:var(--ink)}
  .bt-main{flex:1;overflow-y:auto;padding:32px}
  .bt-wrap{max-width:1180px;margin:0 auto}
  .bt-h2{font-size:22px;font-weight:800;margin:0 0 6px}
  .bt-lead{color:var(--muted);margin:0 0 22px;font-size:15px;max-width:72ch;line-height:1.55}
  .bt-sec{margin-top:40px}
  .bt-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}
  .bt-stat{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:20px 22px}
  .bt-stat small{display:block;color:var(--muted);font-size:14px;margin-bottom:8px}
  .bt-stat b{display:block;font-size:30px;font-weight:800;line-height:1.1}
  .bt-stat span{display:block;color:var(--muted);font-size:13px;margin-top:8px}
  .bt-stat.bt-accent{background:var(--forest);border-color:var(--forest);color:#fff}
  .bt-stat.bt-accent small,.bt-stat.bt-accent span{color:#c9d1c8}
  .bt-stat.bt-accent b{color:var(--gold)}
  .bt-find{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}
  .bt-note{background:var(--card);border:1px solid var(--line);border-left:4px solid var(--gold);border-radius:4px 14px 14px 4px;padding:18px 22px}
  .bt-note h4{margin:0 0 6px;font-size:16px;font-weight:700}
  .bt-note p{margin:0;color:#3d4a40;font-size:14.5px;line-height:1.55}
  .bt-panel{background:var(--card);border:1px solid var(--line);border-radius:14px;overflow:hidden}
  .bt-panel-h{display:flex;justify-content:space-between;align-items:baseline;gap:16px;padding:16px 22px;border-bottom:1px solid var(--line)}
  .bt-panel-h h3{margin:0;font-size:17px;font-weight:700}
  .bt-panel-h span{color:var(--muted);font-size:13px}
  .bt-row{display:grid;grid-template-columns:minmax(150px,1.3fr) 3fr auto;gap:16px;align-items:center;padding:12px 22px;border-bottom:1px solid var(--soft)}
  .bt-row:last-child{border-bottom:0}
  .bt-row .bt-n{font-weight:600;font-size:14.5px;line-height:1.3}
  .bt-row .bt-n em{display:block;font-style:normal;font-weight:400;color:var(--muted);font-size:12.5px}
  .bt-track{height:10px;background:var(--soft);border-radius:6px;overflow:hidden}
  .bt-fill{height:100%;background:var(--forest2);border-radius:6px;transition:width .35s ease}
  .bt-row.bt-lead-row .bt-fill{background:var(--gold)}
  .bt-v{text-align:right;font-variant-numeric:tabular-nums;font-weight:700;font-size:14.5px;min-width:110px}
  .bt-v em{display:block;font-style:normal;font-weight:400;color:var(--muted);font-size:12.5px}
  .bt-seats{display:inline-flex;gap:3px;margin-left:10px;vertical-align:middle}
  .bt-seats i{width:9px;height:9px;border-radius:50%;background:var(--gold);display:inline-block}
  .bt-table{width:100%;border-collapse:collapse;font-size:14px}
  .bt-table th{text-align:left;font-weight:600;color:var(--muted);font-size:13px;padding:11px 22px;border-bottom:1px solid var(--line);background:#faf9f5}
  .bt-table td{padding:11px 22px;border-bottom:1px solid var(--soft);font-variant-numeric:tabular-nums}
  .bt-table tr:last-child td{border-bottom:0}
  .bt-table td.r,.bt-table th.r{text-align:right}
  .bt-up{color:#2f7a45;font-weight:600}.bt-down{color:#a2402f;font-weight:600}
  .bt-grid2{display:grid;grid-template-columns:1.35fr 1fr;gap:20px;align-items:start}
  .bt-chips{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:20px}
  .bt-chip{background:var(--card);border:1px solid var(--line);color:var(--ink);padding:9px 16px;border-radius:999px;font-weight:600;font-size:14px;cursor:pointer}
  .bt-chip:hover{border-color:var(--forest2)}
  .bt-chip[aria-pressed=true]{background:var(--forest);border-color:var(--forest);color:#fff}
  .bt-inline{display:flex;align-items:center;gap:10px;flex-wrap:wrap;color:var(--muted);font-size:14px;margin-bottom:18px}
  .bt-seg{display:inline-flex;border:1px solid var(--line);border-radius:10px;overflow:hidden;background:var(--card)}
  .bt-seg button{border:0;background:transparent;padding:7px 14px;font-weight:600;cursor:pointer;color:var(--ink)}
  .bt-seg button[aria-pressed=true]{background:var(--gold);color:var(--forest)}
  .bt-tag{display:inline-block;background:var(--gold-s);color:var(--gold-d);font-size:12px;font-weight:700;padding:3px 9px;border-radius:999px;margin-left:8px;vertical-align:middle}
  .bt-stat .bt-tag{display:inline-block;margin:6px 0 0}
  .bt-list{margin:0;padding:14px 22px;columns:2;column-gap:28px;font-size:13.5px;color:#3d4a40;list-style:none}
  .bt-list li{padding:4px 0;break-inside:avoid}
  .bt-sim{display:grid;grid-template-columns:1fr 1.1fr;gap:20px;align-items:start}
  .bt-slider{display:grid;grid-template-columns:1fr 150px 64px;gap:14px;align-items:center;padding:10px 22px;border-bottom:1px solid var(--soft);font-size:14px}
  .bt-slider:last-child{border-bottom:0}
  .bt-slider input{width:100%;accent-color:var(--forest2)}
  .bt-slider output{text-align:right;font-weight:700;font-variant-numeric:tabular-nums}
  .bt-btn{background:var(--gold);color:var(--forest);border:0;border-radius:10px;padding:9px 16px;font-weight:700;cursor:pointer}
  .bt-btn.ghost{background:transparent;border:1px solid var(--line);color:var(--ink)}
  .bt-src{margin-top:40px;padding-top:18px;border-top:1px solid var(--line);color:var(--muted);font-size:12.5px;line-height:1.6}
  .bt-muted{color:var(--muted)}
  #bt-launch{position:fixed;right:24px;bottom:96px;z-index:9980;background:var(--bt-gold,#C8A560);color:#13273D;border:0;border-radius:12px;padding:13px 20px;font-weight:700;font-family:inherit;box-shadow:0 6px 20px rgba(38,53,42,.25);cursor:pointer}
  @media (max-width:900px){.bt-stats{grid-template-columns:repeat(2,1fr)}.bt-find,.bt-grid2,.bt-sim{grid-template-columns:1fr}.bt-main{padding:20px 16px}.bt-top{padding:14px 16px 0}.bt-row{grid-template-columns:1fr auto}.bt-row .bt-track{grid-column:1/-1;order:3}.bt-list{columns:1}.bt-slider{grid-template-columns:1fr 110px 56px;padding:10px 16px}}
  @media (prefers-reduced-motion:reduce){.bt-fill{transition:none}}
  `;

  /* ---------- componentes ---------- */
  function barras(items, opts = {}) {
    const max = Math.max(...items.map(i => i.v), 1);
    return items.map((it, i) => `
      <div class="bt-row${i === 0 && opts.destacar !== false ? ' bt-lead-row' : ''}">
        <div class="bt-n">${esc(it.label)}${it.sub ? `<em>${esc(it.sub)}</em>` : ''}</div>
        <div class="bt-track"><div class="bt-fill" style="width:${(it.v / max * 100).toFixed(1)}%"></div></div>
        <div class="bt-v">${fmt(it.v)}${it.seats ? `<span class="bt-seats" aria-label="${it.seats} curules">${'<i></i>'.repeat(it.seats)}</span>` : ''}<em>${it.p != null ? pct(it.p) : ''}${it.extra ? ' · ' + it.extra : ''}</em></div>
      </div>`).join('');
  }
  const panel = (titulo, meta, cuerpo) => `<div class="bt-panel"><div class="bt-panel-h"><h3>${titulo}</h3>${meta ? `<span>${meta}</span>` : ''}</div>${cuerpo}</div>`;
  const cambio = (a, b, pp = true) => {
    if (a == null || b == null) return '<span class="bt-muted">—</span>';
    const d = b - a; const cls = d > 0.0005 ? 'bt-up' : d < -0.0005 ? 'bt-down' : 'bt-muted';
    return `<span class="${cls}">${d > 0 ? '+' : ''}${pp ? (d * 100).toLocaleString('es-CO', { maximumFractionDigits: 1 }) + ' pp' : fmt(d)}</span>`;
  };

  /* ---------- cálculos base ---------- */
  const C = D.concejo;
  const rep23 = repartir(C.partidos.map(p => ({ n: p.n, v: p.v })), D.concejo_blanco, CURULES_CONCEJO);
  const listasConCurul = Object.keys(rep23.seats).length;
  const AL = D.alcaldia;
  const comunas = Object.keys(D.jal).sort((a, b) => (a.startsWith('Corr') - b.startsWith('Corr')) || a.localeCompare(b, 'es', { numeric: true }));
  const R = D.resumen.CONCEJO;

  /* ---------- vistas ---------- */
  function vResumen() {
    const [g1, g2] = AL.cands;
    const urbanas = comunas.filter(c => c.startsWith('Comuna'));
    const pactoPrimero = urbanas.filter(c => D.jal[c].partidos[0].n === 'PACTO HISTORICO').length;
    const c23 = C.por_comuna;
    const tot = k => (c23[k] || []).find(x => x[0] === '__total')[1];
    const peso23 = (tot('Comuna 2') + tot('Comuna 3')) / C.total;
    const pactoVerde = C.partidos.filter(p => ['PACTO HISTORICO', 'PARTIDO ALIANZA VERDE'].includes(p.n)).reduce((s, p) => s + p.v, 0);
    const filas = [
      ['Votos a listas', R.m19.validos, R.m23.validos, false],
      ['Voto en blanco', R.m19.blanco, R.m23.blanco, true],
      ['Votos nulos', R.m19.nulo, R.m23.nulo, true],
      ['Tarjetas no marcadas', R.m19.nomarcado, R.m23.nomarcado, true],
      ['Voto solo por el logo', R.m19.logo, R.m23.logo, true]
    ];
    return `
    <h2 class="bt-h2">Soacha llega a 2027 sin dueño</h2>
    <p class="bt-lead">El alcalde ganó con el aval de La U, el Concejo quedó repartido entre ${listasConCurul} listas y el Pacto Histórico, primera lista en Concejo y ediles, no logró trasladar ese voto a su candidato a la Alcaldía.</p>
    <div class="bt-stats">
      <div class="bt-stat bt-accent"><small>Alcaldía 2023</small><b>${pct(g1[2] / AL.validos)}</b><span>${esc(g1[0].split(' ').slice(-1)[0].replace(/[“”]/g, ''))} ganó por ${fmt(g1[2] - g2[2])} votos</span></div>
      <div class="bt-stat"><small>Participación en alcaldía</small><b>${pct(AL.sufragantes / AL.potencial)}</b><span>${fmt(AL.sufragantes)} de ${fmt(AL.potencial)} habilitados</span></div>
      <div class="bt-stat"><small>Listas con curul en el Concejo</small><b>${listasConCurul}</b><span>Se repartieron ${CURULES_CONCEJO} curules</span></div>
      <div class="bt-stat"><small>Votos para la última curul</small><b>${fmt(rep23.cifra)}</b><span>Cifra repartidora 2023, punto de partida para 2027</span></div>
    </div>

    <div class="bt-sec"><h2 class="bt-h2">Lo que muestran los resultados</h2>
      <div class="bt-find">
        <div class="bt-note"><h4>El voto sigue a las personas, no a las etiquetas</h4><p>Pacto Histórico y Alianza Verde sumaron ${fmt(pactoVerde)} votos en sus listas al Concejo, pero su candidato común a la Alcaldía obtuvo ${fmt(AL.cands[2][2])}. La Alcaldía se decidió entre dos maquinarias personales: Perico (${pct(g1[2] / AL.validos)}) y el candidato del oficialismo saliente (${pct(g2[2] / AL.validos)}).</p></div>
        <div class="bt-note"><h4>Un Concejo de minorías</h4><p>La lista más votada tuvo ${pct(C.partidos[0].s)} de los votos a listas. Con ${CURULES_CONCEJO} curules, la última se ganó con ${fmt(rep23.cifra)} votos: ninguna fuerza puede gobernar el Concejo sin acuerdos de al menos cuatro bancadas.</p></div>
        <div class="bt-note"><h4>Dos comunas definen la elección</h4><p>Las comunas 2 y 3 aportaron el ${pct(peso23, 0)} del voto al Concejo. La Comuna 4 es la de menor volumen urbano (${fmt(tot('Comuna 4'))} votos), con alto margen de crecimiento por participación.</p></div>
        <div class="bt-note"><h4>El Pacto domina las JAL urbanas</h4><p>Fue primera fuerza en ${pactoPrimero} de ${urbanas.length} comunas urbanas. En los corregimientos, en cambio, ganaron Liberal y Cambio Radical, con volúmenes pequeños.</p></div>
      </div>
    </div>

    <div class="bt-sec"><h2 class="bt-h2">Concejo: cómo cambió el voto entre 2019 y 2023</h2>
      <p class="bt-lead">Más votos, más listas y más voto por el logo: el electorado creció, pero se dispersó.</p>
      ${panel('Indicadores del Concejo', 'Soacha', `<table class="bt-table"><thead><tr><th>Indicador</th><th class="r">2019</th><th class="r">2023</th><th class="r">Cambio</th></tr></thead><tbody>
        ${filas.map(f => `<tr><td>${f[0]}</td><td class="r">${f[3] ? pct(f[1]) : fmt(f[1])}</td><td class="r">${f[3] ? pct(f[2]) : fmt(f[2])}</td><td class="r">${f[3] ? cambio(f[1], f[2]) : `<span class="bt-up">+${pct(f[2] / f[1] - 1)}</span>`}</td></tr>`).join('')}
        <tr><td>Número efectivo de partidos</td><td class="r">${R.m19.nep.toFixed(1)}</td><td class="r">${R.m23.nep.toFixed(1)}</td><td class="r"><span class="bt-up">+${(R.m23.nep - R.m19.nep).toFixed(1)}</span></td></tr>
      </tbody></table>`)}
    </div>`;
  }

  function vAlcaldia() {
    const items = AL.cands.map(c => ({ label: c[0], sub: c[1], v: c[2], p: c[2] / AL.validos }));
    const [g1, g2, g3, g4] = AL.cands;
    return `
    <h2 class="bt-h2">Alcaldía 2023</h2>
    <p class="bt-lead">Elección a una sola vuelta. ${fmt(AL.sufragantes)} sufragantes, ${fmt(AL.validos)} votos válidos y ${fmt(AL.blanco)} en blanco.</p>
    <div class="bt-grid2">
      ${panel('Resultado por candidato', '% sobre votos válidos', barras(items))}
      <div style="display:grid;gap:16px">
        <div class="bt-note"><h4>Una contienda de dos bloques</h4><p>Los dos primeros sumaron ${pct((g1[2] + g2[2]) / AL.validos, 0)} de los válidos. El tercero quedó a más de ${fmt(g2[2] - g3[2])} votos del segundo.</p></div>
        <div class="bt-note"><h4>2027 es una silla abierta</h4><p>El alcalde en ejercicio no puede reelegirse para el periodo siguiente, así que la disputa será por heredar su coalición o capturar el bloque de ${fmt(g2[2])} votos que acompañó al oficialismo anterior.</p></div>
        <div class="bt-note"><h4>Voto independiente disponible</h4><p>${esc(g4[0])} (${esc(g4[1])}) reunió ${fmt(g4[2])} votos sin estructura de partido tradicional. Es el bloque más barato de disputar para 2027.</p></div>
      </div>
    </div>`;
  }

  function vConcejo() {
    const items = C.partidos.slice(0, 14).map(p => ({
      label: nom(p.n), v: p.v, p: p.s, seats: rep23.seats[p.n] || 0,
      sub: p.logo === p.v ? 'Lista cerrada' : `${p.cands} candidatos · ${pct(p.logo / p.v, 0)} voto por logo`
    }));
    const hist = C.partidos.filter(p => p.s19 != null).map(p => `<tr><td>${esc(nom(p.n))}${p.ant ? `<span class="bt-muted"> · en 2019: ${esc(p.ant)}</span>` : ''}</td><td class="r">${pct(p.s19)}</td><td class="r">${pct(p.s)}</td><td class="r">${cambio(p.s19, p.s)}</td></tr>`).join('');
    const cands = C.candidatos.slice(0, 15).map(c => `<tr><td><b>${esc(persona(c.n))}</b><br><span class="bt-muted">${esc(nom(c.pt))}</span></td><td class="r">${fmt(c.v)}</td><td class="r">${c.v19 ? fmt(c.v19) : '<span class="bt-muted">Nuevo</span>'}</td><td class="r">${c.v19 ? cambio(c.v19, c.v, false) : ''}</td><td class="r">${c.np}</td></tr>`).join('');
    const pc = Object.entries(C.por_comuna).filter(([k]) => k !== 'Sin asignar').map(([k, arr]) => {
      const t = arr.find(x => x[0] === '__total')[1];
      return { label: k, v: t, p: t / C.total, sub: `Primera fuerza: ${nom(arr[0][0])} (${pct(arr[0][1] / t)})` };
    }).sort((a, b) => b.v - a.v);
    const puestos = C.puestos.slice(0, 12).map(p => `<tr><td><b>${esc(tc(p.n))}</b><br><span class="bt-muted">${esc(p.c)}</span></td><td class="r">${fmt(p.t)}</td><td>${esc(nom(p.top[0][0]))} <span class="bt-muted">${pct(p.top[0][1] / p.t)}</span></td><td>${esc(nom(p.top[1][0]))} <span class="bt-muted">${pct(p.top[1][1] / p.t)}</span></td></tr>`).join('');
    return `
    <h2 class="bt-h2">Concejo municipal</h2>
    <p class="bt-lead">${fmt(C.total)} votos a listas y ${fmt(D.concejo_blanco)} en blanco. Cociente electoral de ${fmt(rep23.cociente)} votos, umbral de ${fmt(rep23.umbral)} y cifra repartidora de ${fmt(rep23.cifra)}. Los puntos dorados son las curules calculadas, que coinciden con la composición publicada del Concejo 2024–2027.</p>
    ${panel('Votos por lista', `${CURULES_CONCEJO} curules`, barras(items))}
    <div class="bt-sec bt-grid2">
      ${panel('Candidatos más votados', 'Votos 2023 frente a 2019', `<table class="bt-table"><thead><tr><th>Candidato</th><th class="r">2023</th><th class="r">2019</th><th class="r">Cambio</th><th class="r">Puestos</th></tr></thead><tbody>${cands}</tbody></table>`)}
      <div style="display:grid;gap:20px">
        ${panel('Participación por lista', 'Comparable con 2019', `<table class="bt-table"><thead><tr><th>Lista</th><th class="r">2019</th><th class="r">2023</th><th class="r">Cambio</th></tr></thead><tbody>${hist}</tbody></table>`)}
        ${panel('Voto al Concejo por comuna', '', barras(pc, { destacar: false }))}
      </div>
    </div>
    <div class="bt-sec">${panel('Puestos de votación con más votos', `${C.puestos.length} puestos en el municipio`, `<table class="bt-table"><thead><tr><th>Puesto</th><th class="r">Votos</th><th>Primera fuerza</th><th>Segunda fuerza</th></tr></thead><tbody>${puestos}</tbody></table>`)}</div>`;
  }

  const estado = { comuna: 'Comuna 2', curulesJal: 7, blancoJal: false };
  function vEdiles() {
    const J = D.jal[estado.comuna];
    const blanco = estado.blancoJal ? J.total * D.jal_blanco_ratio : 0;
    const r = repartir(J.partidos.map(p => ({ n: p.n, v: p.v })), blanco, estado.curulesJal);
    const items = J.partidos.slice(0, 10).map(p => ({ label: nom(p.n), v: p.v, p: p.v / J.total, seats: r.seats[p.n] || 0, sub: p.logo === p.v ? 'Lista cerrada' : `${p.cands} candidatos` }));
    const cands = J.candidatos.slice(0, 10).map(c => `<tr><td><b>${esc(persona(c.n))}</b><br><span class="bt-muted">${esc(nom(c.pt))}</span></td><td class="r">${fmt(c.v)}</td></tr>`).join('');
    const resumen = comunas.map(k => { const j = D.jal[k]; const a = j.partidos[0], b = j.partidos[1];
      return `<tr><td><b>${k}</b></td><td class="r">${fmt(j.total)}</td><td>${esc(nom(a.n))} <span class="bt-muted">${pct(a.v / j.total)}</span></td><td>${b ? esc(nom(b.n)) + ` <span class="bt-muted">${pct(b.v / j.total)}</span>` : ''}</td><td class="r">${pct((a.v - (b ? b.v : 0)) / j.total)}</td></tr>`; }).join('');
    return `
    <h2 class="bt-h2">Ediles por comuna</h2>
    <p class="bt-lead">Resultados 2023 de las Juntas Administradoras Locales. Elija la comuna y el número de ediles para ver el reparto de curules.</p>
    <div class="bt-chips" role="group" aria-label="Comuna">${comunas.map(k => `<button class="bt-chip" data-comuna="${k}" aria-pressed="${k === estado.comuna}">${k}</button>`).join('')}</div>
    <div class="bt-inline">Ediles a elegir <div class="bt-seg" role="group">${[5, 7, 9].map(n => `<button data-cur="${n}" aria-pressed="${n === estado.curulesJal}">${n}</button>`).join('')}</div></div><div class="bt-inline">Voto en blanco <div class="bt-seg" role="group"><button data-bj="0" aria-pressed="${!estado.blancoJal}">Sin incluir</button><button data-bj="1" aria-pressed="${estado.blancoJal}">Estimado (${pct(D.jal_blanco_ratio, 0)})</button></div><span>La base no trae el voto en blanco por comuna. Confirme el número de ediles en el acuerdo municipal.</span></div>
    <div class="bt-stats">
      <div class="bt-stat bt-accent"><small>Primera fuerza</small><b style="font-size:24px">${esc(nom(J.partidos[0].n))}</b><span>${pct(J.partidos[0].v / J.total)} de los votos a listas</span></div>
      <div class="bt-stat"><small>Votos a listas</small><b>${fmt(J.total)}</b><span>${J.puestos.length} puestos de votación</span></div>
      <div class="bt-stat"><small>Votos para la última curul</small><b>${fmt(r.cifra)}</b><span>Cifra repartidora${estado.blancoJal ? ' con blanco estimado' : ' sin voto en blanco'}<span class="bt-tag">Estimado</span></span></div>
      <div class="bt-stat"><small>Umbral</small><b>${fmt(r.umbral)}</b><span>50 % del cociente electoral</span></div>
    </div>
    <div class="bt-sec bt-grid2">
      ${panel(`Listas en ${estado.comuna}`, `${estado.curulesJal} ediles`, barras(items))}
      <div style="display:grid;gap:20px">
        ${panel('Candidatos más votados', '', `<table class="bt-table"><tbody>${cands}</tbody></table>`)}
        ${panel('Puestos de votación', '', `<ul class="bt-list">${J.puestos.map(p => `<li>${esc(tc(p))}</li>`).join('')}</ul>`)}
      </div>
    </div>
    <div class="bt-sec">${panel('Todas las comunas', 'Primera y segunda fuerza, y ventaja', `<table class="bt-table"><thead><tr><th>Comuna</th><th class="r">Votos</th><th>Primera fuerza</th><th>Segunda fuerza</th><th class="r">Ventaja</th></tr></thead><tbody>${resumen}</tbody></table>`)}</div>`;
  }

  const sim = { part: 0, blanco: D.concejo_blanco / (C.total + D.concejo_blanco), aj: {} };
  const SIM_LISTAS = C.partidos.slice(0, 12);
  function calcularSim() {
    const factor = 1 + sim.part / 100;
    const listas = C.partidos.map(p => ({ n: p.n, v: p.v * factor * (1 + (sim.aj[p.n] || 0) / 100) }));
    const tl = listas.reduce((s, l) => s + l.v, 0);
    const blanco = tl * sim.blanco / (1 - sim.blanco);
    return { r: repartir(listas, blanco, CURULES_CONCEJO), listas };
  }
  function resultadoSim() {
    const { r, listas } = calcularSim();
    const orden = listas.filter(l => r.seats[l.n] || SIM_LISTAS.find(s => s.n === l.n)).sort((a, b) => b.v - a.v).slice(0, 13);
    const items = orden.map(l => { const base = rep23.seats[l.n] || 0, now = r.seats[l.n] || 0;
      return { label: nom(l.n), v: l.v, seats: now, sub: now === base ? `Igual que 2023 (${base})` : `${now > base ? '+' : ''}${now - base} frente a 2023` }; });
    return `
      <div class="bt-stats" style="grid-template-columns:repeat(3,1fr)">
        <div class="bt-stat bt-accent"><small>Votos para la última curul</small><b>${fmt(r.cifra)}</b><span>${cambio(rep23.cifra, r.cifra, false)} frente a 2023</span></div>
        <div class="bt-stat"><small>Umbral</small><b>${fmt(r.umbral)}</b><span>Mínimo para que una lista compita</span></div>
        <div class="bt-stat"><small>Listas con curul</small><b>${Object.keys(r.seats).length}</b><span>En 2023: ${listasConCurul}</span></div>
      </div>
      <div class="bt-sec" style="margin-top:20px">${panel('Curules proyectadas', `${CURULES_CONCEJO} curules`, barras(items))}</div>`;
  }
  function vSimulador() {
    const sl = SIM_LISTAS.map(p => `<div class="bt-slider"><label for="bt-s-${esc(p.n)}">${esc(nom(p.n))}</label><input type="range" id="bt-s-${esc(p.n)}" data-lista="${esc(p.n)}" min="-60" max="60" step="5" value="${sim.aj[p.n] || 0}"><output>${(sim.aj[p.n] || 0) > 0 ? '+' : ''}${sim.aj[p.n] || 0} %</output></div>`).join('');
    return `
    <h2 class="bt-h2">Simulador del Concejo 2027</h2>
    <p class="bt-lead">Parte de los resultados de 2023 y ajuste la participación y la fuerza de cada lista. El reparto aplica umbral del 50 % del cociente y cifra repartidora, como en la elección real. Entre 2019 y 2023 los votos a listas crecieron ${pct(R.m23.validos / R.m19.validos - 1)}.</p>
    <div class="bt-sim">
      <div style="display:grid;gap:20px">
        ${panel('Escenario', '<button class="bt-btn ghost" data-reset>Restablecer 2023</button>', `
          <div class="bt-slider"><label for="bt-part">Cambio en participación</label><input type="range" id="bt-part" min="-20" max="30" step="1" value="${sim.part}"><output>${sim.part > 0 ? '+' : ''}${sim.part} %</output></div>
          <div class="bt-slider"><label for="bt-blanco">Voto en blanco</label><input type="range" id="bt-blanco" min="5" max="30" step="1" value="${Math.round(sim.blanco * 100)}"><output>${Math.round(sim.blanco * 100)} %</output></div>`)}
        ${panel('Fuerza de cada lista', 'Variación sobre 2023', sl)}
      </div>
      <div id="bt-sim-out">${resultadoSim()}</div>
    </div>`;
  }

  const VISTAS = [['resumen', 'Resumen', vResumen], ['alcaldia', 'Alcaldía', vAlcaldia], ['concejo', 'Concejo', vConcejo], ['ediles', 'Ediles por comuna', vEdiles], ['simulador', 'Simulador 2027', vSimulador]];
  let actual = 'resumen';

  /* ---------- montaje ---------- */
  let root;
  function construir() {
    const st = document.createElement('style'); st.id = 'bt-style'; st.textContent = CSS; document.head.appendChild(st);
    root = document.createElement('div'); root.id = 'bt-root'; root.setAttribute('role', 'dialog'); root.setAttribute('aria-modal', 'true'); root.setAttribute('aria-labelledby', 'bt-title');
    root.innerHTML = `
      <div class="bt-top"><div class="bt-top-row"><div><p class="bt-kicker">Análisis territorial</p><h1 class="bt-title" id="bt-title">SOACHA</h1><p class="bt-sub">Resultados 2023 y base para las elecciones territoriales de 2027</p></div>
      <button class="bt-close" data-close>Cerrar análisis</button></div>
      <div class="bt-nav" role="tablist">${VISTAS.map(v => `<button role="tab" data-vista="${v[0]}" aria-selected="${v[0] === actual}">${v[1]}</button>`).join('')}</div></div>
      <div class="bt-main"><div class="bt-wrap"><div id="bt-body"></div>
      <div class="bt-src">Fuentes: base Brújula Electoral (resultados de preconteo de la Registraduría, territoriales 2019 y 2023) y boletín 38 de la Registraduría para Alcaldía 2023. Las curules se calculan con la regla de cifra repartidora; en ediles, el voto en blanco por comuna no está en la base: puede excluirse o estimarse con la proporción municipal de JAL (${pct(D.jal_blanco_ratio, 0)} sobre votos a listas). Un puesto (Colegio Bolívar Primaria) no tiene comuna asignada en la base.</div></div></div>`;
    document.body.appendChild(root);
    root.addEventListener('click', onClick);
    root.addEventListener('input', onInput);
    document.addEventListener('keydown', e => { if (e.key === 'Escape' && root.classList.contains('bt-open')) close(); });
    pintar();
  }
  function pintar() {
    const v = VISTAS.find(x => x[0] === actual);
    root.querySelector('#bt-body').innerHTML = v[2]();
    root.querySelectorAll('[data-vista]').forEach(b => b.setAttribute('aria-selected', b.dataset.vista === actual));
  }
  function onClick(e) {
    const t = e.target.closest('button'); if (!t) return;
    if (t.hasAttribute('data-close')) return close();
    if (t.dataset.vista) { actual = t.dataset.vista; pintar(); root.querySelector('.bt-main').scrollTop = 0; return; }
    if (t.dataset.comuna) { estado.comuna = t.dataset.comuna; pintar(); return; }
    if (t.dataset.cur) { estado.curulesJal = +t.dataset.cur; pintar(); return; }
    if (t.dataset.bj) { estado.blancoJal = t.dataset.bj === '1'; pintar(); return; }
    if (t.hasAttribute('data-reset')) { sim.part = 0; sim.blanco = D.concejo_blanco / (C.total + D.concejo_blanco); sim.aj = {}; pintar(); }
  }
  function onInput(e) {
    const el = e.target; if (el.type !== 'range') return;
    const v = +el.value;
    if (el.id === 'bt-part') { sim.part = v; el.nextElementSibling.textContent = (v > 0 ? '+' : '') + v + ' %'; }
    else if (el.id === 'bt-blanco') { sim.blanco = v / 100; el.nextElementSibling.textContent = v + ' %'; }
    else if (el.dataset.lista) { sim.aj[el.dataset.lista] = v; el.nextElementSibling.textContent = (v > 0 ? '+' : '') + v + ' %'; }
    root.querySelector('#bt-sim-out').innerHTML = resultadoSim();
  }
  let ultimoFoco;
  function open() { if (!root) construir(); ultimoFoco = document.activeElement; root.classList.add('bt-open'); document.body.style.overflow = 'hidden'; root.querySelector('[data-close]').focus(); }
  function close() { root.classList.remove('bt-open'); document.body.style.overflow = ''; if (ultimoFoco) ultimoFoco.focus(); }

  function insertarPestana() {
    if (document.getElementById('bt-tab')) return true;
    const ref = [...document.querySelectorAll('button,a,[role=tab]')].find(el => el.textContent.trim() === 'Partidos y tendencias');
    if (!ref) return false;
    const tab = ref.cloneNode(false);
    tab.id = 'bt-tab'; tab.textContent = 'Análisis territorial';
    tab.removeAttribute('aria-selected'); tab.removeAttribute('href');
    [...tab.attributes].forEach(at => { if (/^(data-|on)/.test(at.name)) tab.removeAttribute(at.name); });
    tab.addEventListener('click', e => { e.preventDefault(); e.stopPropagation(); open(); }, true);
    ref.parentNode.insertBefore(tab, ref.nextSibling);
    const f = document.getElementById('bt-launch'); if (f) f.remove();
    return true;
  }
  function botonFlotante() {
    if (document.getElementById('bt-launch') || document.getElementById('bt-tab')) return;
    const b = document.createElement('button'); b.id = 'bt-launch'; b.textContent = 'Análisis territorial';
    b.addEventListener('click', open); document.body.appendChild(b);
  }
  function iniciar() {
    if (!document.getElementById('bt-style')) { const s = document.createElement('style'); s.textContent = CSS.split('#bt-root{')[0] + '#bt-launch' + CSS.split('#bt-launch')[1].split('@media')[0]; document.head.appendChild(s); }
    if (!insertarPestana()) botonFlotante();
    new MutationObserver(() => { if (!document.getElementById('bt-tab')) insertarPestana(); }).observe(document.body, { childList: true, subtree: true });
  }
  window.BrujulaTerritorial = { open, close };
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', iniciar); else iniciar();
})();
